classDiagram
    class Person {
        firstName: string
        lastName: string
        salutation: string
        gender: string
        birthday: Time
        email: string
        phone: string
        active: bool
        deceased: bool
    }

    class Place {
        addressLine1: string
        addressLine2: string
        city: string
        state: string
        zip: string
        mailingConsentGranted: bool
    }

    class Organization {
        name: string
        updatedAt: Time
    }
