site_name: Indigo CNS Documentation
site_url: http://localhost:8000
theme:
  name: material
  palette:
    primary: deep purple
nav:
  - Home: index.md
  - Features: features.md
  - Specification:
    - Terminology: specifications/terminology.md
    - Design: specifications/design.md
    - REST API: specifications/api.md
    - Security: specifications/security.md
  - Administration Guide:
    - Installation: administration-guide/installation.md
    - Database Setup: administration-guide/database.md
    - Authentication: administration-guide/authentication.md
    - Grants: administration-guide/grants.md
    - Branding: administration-guide/branding.md
  - User Manual:
    - Stub: manual_stub.md
  - About:
    - License: license.md
    - Project Authors: authors.md
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - markdown.extensions.abbr
