classDiagram
    class Person {
        string firstName
        string lastName
        string salutation
        string gender
        Time birthday
        string email
        string phone
        bool active
        bool deceased

        search() string
    }

    class Place {
        string addressLine1
        string addressLine2
        string city
        string state
        string zip
        bool mailingConsentGranted

        search() string
    }

    class Organization {
        string name
        Time updatedAt

        search() string
    }

    class AddressPhone {
        string addressLine1
        string addressLine2
        string city
        string state
        string zip
        string county
        string serviceArea
        string routePresort
        bool validAddress
        bool deceased
        array serviceMemberships
        string otherAddress
        string email
        string internet
        string notes
        string phone
        string phoneExtension
        string phoneType
    }

    class Alias {
        string firstName
        string lastName
        bool contactInEmail
    }

    class RecordDef {
        string recordType
        string defaultGrant
    }

    class InformationAndReferral {
        dateTime initialDate
        string category
        string regarding
        string outcome
        string date
        string employee
        string grant 
        string serviceType
        int hours

        add()
        edit()
    }

    class DisabilityInfo {
        array disabilities
        string disabilityClassification
        string raceEthnicity
        string gender
    }

    class CustomerService {
        int customerServiceFileNumber
        string status
        dateTime activationDate
        dateTime closureDate
        dateTime dateOfBirth
        string independentLivingActivity
        bool deceased
        string intake
        string exit 
        dateTime ILPActionDate
        dateTime date
        string primaryEmployee
        string grant
        string type 
        int hours

        add()
        edit()
    }

    class Goals {
        dateTime initialDate
        string type
        string futureReference
        string grant
        string goalStatus
        dateTime estimatedCompletionDate
        string goalDescription
        string outcome
        string outcomeDescription
        dateTime closureDate

        add()
        edit()
    }

    class CommunityServiceEvent {
        dateTime initialDate
        string category
        string futureReference
        string serviceDescription
        string outcome
        int publications
        int personsWithDisabilities
        int generalPublic
    }

    class ServicesOffered {
        string serviceDescription
        array eligibilityRequirments
        array intakeProcedures
        array feesCharged
        string hoursOfOperation
        string other
    }

    %% Relationships
    AddressPhone <|-- Place : 1 "is a" 1
    Person "1" --> "0..*" AddressPhone : has
    Person "1" --> "0..*" Alias : can have
    Person "1" --> "0..*" RecordDef : has
    Person "1" --> "0..1" DisabilityInfo : has
    Person "1" --> "0..*" InformationAndReferral : has
    Person "1" --> "0..*" CustomerService : has
    Person "1" --> "0..*" Goals : sets
    CustomerService "1" --> "1..*" ServicesOffered
    AddressPhone "1" --> "1..*" ServicesOffered : has
