---
config:
  layout: elk
---
classDiagram
    class Employee {
        UUIDv4 id
        string username
        string firstName
        string lastName
        bool active
    }
    note for Employee "unique(username)"
    note for Employee "Usernames are assumed to be mutable, therefore a static ID is also set"
    note for Employee "Data populated from AD upon successful auth"
    note for Employee "TODO: populate id from some AD attribute?"
    
    Individual "n" --> "1" Employee
    Individual "n" -- "m" Disability: *Associative Table
    Individual .. Place
    class Individual {
        UUIDv4 id
        string firstName
        string lastName
        string salutation
        DateTime birthday
        EnumIndividualDescription description
        string email
        string phone
        bool active
        bool deceased
        Place serviceArea
        ?Employee primaryContact
        ?Place mailingAddress
    }

    Race "n" -- "m" Individual: *Associative Table
    class Race {
        string name
    }
    note for Race "id(name)"
    note for Race "Does this need an 'antiquated' flag or something?"

    Gender "n" -- "m" Individual: *Associative Table
    class Gender {
        UUIDv4 id
        string name
        string pronouns
    }

    Disability "n" --> "1" DisabilityClassification
    class Disability {
        string name
        DisabilityClassification classification
    }
    note for Disability "id(name)"
    note for Disability "Do names need to be mutable? If so, this needs a separate UUID."

    class DisabilityClassification {
        string name
    }
    note for DisabilityClassification "id(name)"

    class Place {
        <<embeddable>>
        string address
        string city
        string state
        string zip
    }

    Organization .. Place
    class Organization {
        UUIDv4 id
        string name
        Place[] address
        Time updatedAt
    }
    note for Organization "Why is address an array? Can this be a single value?"

    InformationAndReferral "n" --> "1" Grant
    InformationAndReferral "1" --> "1" Individual
    InformationAndReferral "n" --> "1" Employee
    InformationAndReferral .. Place
    class InformationAndReferral {
        date date
        date initialDate
        Employee primaryContact
        EnumCategory category
        EnumGrants grant
        EnumIrServiceType serviceType
        int hours
        text outcomeDescription
        text regarding
    }

    ConsumerService "n" --> "1" Grant
    ConsumerService "n" --> "1" Individual
    class ConsumerService {
        int consumerServiceFileNumber
        date activatesAt
        date closesAt
        date date
        date ILPActionDate
        DateTime createdAt
        Employee primaryEmployee
        EnumConsumerType type
        EnumGrants grant
        EnumIndependentLivingActivity independentLivingActivity
        EnumConsumerPersonalStatus intake
        EnumConsumerPersonalStatus exit
        EnumConsumerRecordStatus status
    }
    note for ConsumerService "primaryEmployee should not be a string. It should be an FK to an employee."
    note for ConsumerService "Grant should be an FK to a Grant object of some sort"
    note for ConsumerService "The hours property does not track by employee. Should hours be calculated from some sort of 'Update' entity in a one-to-many relationship?"

    Update "n" --> "1" ConsumerService
    class Update {
        UUIDv4 id
        ConsumerService regarding
        Employee author
        DateTime createdAt
        TimeInterval duration
        ?string comments
    }

    Attachment "n" --> "1" Update
    class Attachment {
        UUIDv4 id
        Update attachedTo
        string originalName
        string filesystemLocation
        string mime
        int size
    }


    Goal "n" --> "1" Individual
    Goal .. Place
    class Goal {
        date estimatedCompletionDate
        date initialDate
        DateTime closedAt
        DateTime createdAt
        EnumFutureReference futureReference
        EnumGoalStatus goalStatus
        EnumGoalType type
        EnumGoalOutcome goalOutcome
        Individual individual
        text goalDescription
        text outcomeDescription
    }
    note for Goal "How to handle addresses? We can't use arrays in DBMS."

    CommunityServiceEvent .. Place
    CommunityServiceEvent "n" --> "1" Organization
    class CommunityServiceEvent {
        date initialDate
        EnumCategory category
        EnumFutureReference futureReference
        text serviceDescription
        text outcomeDescription
        int publications
        int personsWithDisabilitiesCount
        int generalPublicCount
        bool addressRequired
        Place[] addresses
    }
    note for CommunityServiceEvent "What to do about addresses? Does this also need an update entity?"

    class Grant {
        UUIDv4 id
    }
    note for Grant "What properties are relevant to grants?"
