classDiagram
    class Individual {
        string firstName
        string lastName
        string salutation
        string gender
        Time birthday
        string email
        string phone
        bool active
        bool deceased
        string primaryEmployee
        Place serviceArea
    }

    class Employee {
    	array permissions
        string defaultGrant
    }

    class Place {
    	string address
        string city
        string state
        string zip
    }

    class Organization {
        string name
        Place[] address
        Time updatedAt
    }

    class InformationAndReferral {
        date initialDate
        string category
        string regarding
        string outcome
        string date
        string employee
        string grant 
        string serviceType
        int hours
		bool addressRequired
		array addresses
    }
    
    class Contact {
		string preferredContactMethod
		array email
		array phoneNumber
		array website
    }

    class Memberships {
        array serviceMemberships
        array businessMemberships
        bool mailingConsentGranted
        Place mailingAddress
        string raceEthnicity
        string gender
    }

    class Eligibility {
        array disabilities
        bool hasDisability
        string disabilityClassification
    }

    class ConsumerService {
        int consumerServiceFileNumber
        string status
        date activationDate
        date closureDate
        date dateOfBirth
        string independentLivingActivity
        bool deceased
        string intake
        string exit 
        date ILPActionDate
        date date
        string primaryEmployee
        string grant
        string type 
        int hours
    }

    class Goals {
        date initialDate
        string type
        string futureReference
        string grant
        string goalStatus
        date estimatedCompletionDate
        string goalDescription
        string outcome
        string outcomeDescription
        date closureDate
		bool addressRequired
		Place[] addresses
    }

    class CommunityServiceEvent {
        date initialDate
        string category
        string futureReference
        string serviceDescription
        string outcome
        int publications
        int personsWithDisabilities
        int generalPublic
		bool addressRequired
		Place[] addresses
    }

    class Attachments {
    	string notes
    	array attachments
    }

	%% Relationships
	Individual "1" --> "0..1" Employee : is
	Individual "1" --> "1" Memberships : has
	Individual "1" --> "0..*" InformationAndReferral : has
	Individual "1" --> "1" Eligibility : has
	Individual "1" --> "0..*" ConsumerService : has
	InformationAndReferral "1" --> "1" Employee : has
	ConsumerService "1" --> "1" Employee : has
	ConsumerService "1" --> "0..*" Goals : sets
	Memberships "1" --> "0..1" Organization : has
	Organization "1" --> "0..1" CommunityServiceEvent: has
	InformationAndReferral "1" --> "0..1" Place : has
	Individual "1" --> "1" Place : has
	CommunityServiceEvent "1" --> "0..*" Place : has
	Goals "1" --> "0..*" Place : has
	Memberships "1" --> "0..*" Place : has
	Organization "1" --> "0..*" Place : has
	Individual "1" --> "1" Attachments : has
	Organization "1" --> "1" Attachments : has
	Individual "1" --> "1" Contact : has
	Organization "1" --> "1" Contact : has
