gantt
    title Indigo CIL
    dateFormat  YYYY-MM-DD
    todayMarker off

    section PR1
    Initial Advisor Meeting                     :a01, 2025-09-05, 20d
    Framework Evaluation                        :a03, 2025-09-05, 20d
    Project Proposal                            :a02, 2025-09-05, 20d

    section PR2
    GroupWorks and CIL Info Meeting             :a04, 2025-09-25, 15d
    Backend Entitiy UML                         :a23, 2025-09-25, 15d
    Spin Up Development DB and LDAP             :a24, 2025-09-25, 15d

    section PR3
    Login Mechanism                             :a15, 2025-10-10, 21d
    Active Directory Integration                :a16, 2025-10-10, 21d
    Synthesize UI/UX Ideas                      :a05, 2025-10-10, 21d
    UX Flowchart                                :a26, 2025-10-10, 21d

    section PR4
    Implement Contact Information               :a06, 2025-10-31, 14d
    Implement I&R                               :a08, 2025-10-31, 14d
    File Attachments                            :a13, 2025-10-31, 14d

    section PR5
    Implement CEO                               :a09, 2025-11-14, 20d
    Advanced Search Functionality               :a07, 2025-11-14, 20d
    Request for Information                     :a17, 2025-11-14, 20d
    Consumer Satisfaction Survey                :a20, 2025-11-14, 20d

    section Jan 2026
    Create Dashboard                            :a11, 2026-01-12, 20d
    Create Container Images & Build CI          :a27, 2026-01-12, 20d
    Add SSL Certificate to Frontend             :a22, 2026-01-12, 20d
    Release Sandbox Instance                    :a28, 2026-01-12, 20d

    Section Feb 2026
    Fuzzy Search                                :a25, 2026-02-01, 28d
    Query Builder                               :a14, 2026-02-01, 28d
    Iterate Upon End-User Feedback              :a28, 2026-02-01, 28d

    Section Mar 2026
    Create Consumer Master Lists                :a19, 2026-03-01, 31d
    Calendar Features                           :a12, 2026-03-01, 31d
    Record Deduplication                        :a10, 2026-03-01, 31d
    Second Sandbox Deployment                   :a30, 2026-03-01, 31d

    Section Apr 2026
    Database Migration                          :a18, 2026-04-01, 30d
    Export to PPR / 704 Report                  :a21, 2026-04-01, 30d
    Iterate Upon End-User Feedback              :a31, 2026-04-01, 30d

    Section May 2026
    Options IRCIL Demo                          :a33, 2026-05-01, 14d
    Indigo v1 Release                           :a32, 2026-05-01, 14d
