flowchart TD
	Contact["Subtab: Contact Information"]
	Eligibility["Subtab: Eligibility (formerly Disability Information)"]
	IR["Subtab: Information and Referral (I&R)"]
	ConsumerService["Subtab: Consumer Service Record"]
	Goals["Subtab: Goals"]
	CEO["Subtab: Community, Education, and Outreach (CEO)"]
	Memberships["Subtab: Memberships"]
	Attachments["Subtab: Notes and Attachments"]
	Newsletter["Subtab: Newsletter"]
	
    A["Login Page"] <--> B["Main Dashboard Page"]
    B <--> C["Business Search Page"]
    B <--> D["Individual Search Page"]
    C <--> Business["New Business Record Page (Separate Tab)"]
    D <--> Individual["New Individual Record Page (Separate Tab)"]

    Business --- CEO
    Business --- Contact
	Business --- Attachments
	Business --- Newsletter

    Individual --- Contact
	Individual --- Attachments
	Individual --- Newsletter
 	Individual --- Memberships
 	Individual --- Eligibility
	Individual --- IR
	Individual --- ConsumerService
	Individual --- Goals

