flowchart TD
    A[Login Page] <--> B[Main Dashboard Page]
    B <--> C[Business Search Page]
    B <--> D[Individual Search Page]
    C <--> E[New Business Record Page -separate tab]
    D <--> F[New Individual Record Page -separate tab]
